#!/bin/bash

# Função para exibir uma barra de progresso usando Zenity
exibir_barra_de_progresso() {
    local tempo_total="$1"  # Tempo total em segundos
    local num_segmentos=5   # Número de segmentos (reduzido para 5 para atingir o limite mínimo de 2 segundos)

    local msg_aguarde="Aguarde"
    local msg_seg="seg."
    local msg_fim="Fim da espera"

    # Cálculo dos intervalos de tempo para cada segmento
    local intervalo=$(expr "$tempo_total" / "$num_segmentos")

    # Loop para exibir as mensagens de progresso
    (
    for i in $(seq "$num_segmentos" -1 1); do
        echo "# $msg_aguarde $(expr $i \* $intervalo) $msg_seg"
        sleep "$intervalo"
    done
)|
zenity --progress \
  --title="Progress Status" \
  --text="First Task." \
  --percentage=0 \
  --pulsate \
  --auto-close \
  --auto-kill
}

# Exibe a barra de progresso para 10 segundos
exibir_barra_de_progresso "$@"
